databases:
  - name: repangapi
    databaseName: repangapi
    user: repangapi

services:
  - type: web
    name: repangapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn repangapi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: repangapi
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

