# Generated by Django 4.2.3 on 2023-07-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pan', 'Pan'), ('pastel', 'Pastel'), ('galletas', 'Galletas'), ('pays', 'Pays')], max_length=10, null=True),
        ),
    ]
