# Generated by Django 4.2.3 on 2023-07-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='proveedor',
            field=models.CharField(max_length=200),
        ),
    ]
