# Generated by Django 4.2.3 on 2023-07-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_alter_rawmaterial_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.proveedor'),
        ),
    ]
