# Generated by Django 4.2.3 on 2023-07-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0003_alter_rawmaterial_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='type',
            field=models.CharField(choices=[('TA', 'Tienda de Autoservicio'), ('TL', 'Tienda local'), ('M', 'Mercado')], max_length=3, null=True),
        ),
    ]
