# Generated by Django 4.2.3 on 2023-07-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0004_alter_proveedor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='presentacion',
            new_name='presentation',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='cantidad',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='precio',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='proveedor',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='unidad',
            new_name='units',
        ),
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Supplier',
        ),
        migrations.CreateModel(
            name='RawMaterialSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.IntegerField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.supplier')),
            ],
        ),
    ]
