# Generated by Django 4.2.3 on 2023-07-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0005_rename_marca_rawmaterial_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='suppliers',
            field=models.ManyToManyField(through='raw_materials.RawMaterialSupplier', to='raw_materials.supplier'),
        ),
    ]
