# Generated by Django 4.2.3 on 2023-07-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0006_remove_rawmaterial_supplier_rawmaterial_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rawmaterialsupplier',
            name='offered_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
