# Generated by Django 4.2.3 on 2023-07-26 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0008_remove_rawmaterial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialsupplier',
            name='purchased_date',
            field=models.DateField(default=datetime.date(2023, 7, 25), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialsupplier',
            unique_together={('raw_material', 'supplier')},
        ),
    ]
