# Generated by Django 4.2.3 on 2023-07-26 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0009_rawmaterialsupplier_purchased_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialsupplier',
            name='purchased_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
