# Generated by Django 4.2.3 on 2023-08-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_characteristic_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
