# Generated by Django 4.2.3 on 2023-08-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_presentation_characteristics_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.AddField(
            model_name='presentation',
            name='unique_characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
